export const ADD_STUDENT = "ADD_STUDENT";
export const UPDATE_STUDENT = "UPDATE_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";
export const VIEW_STUDENT = "VIEW_STUDENT";
export const SEARCH_STUDENT = "SEARCH_STUDENT";
